# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application set up

on:
  # pull_request:
  push:
    branches: [ main ]

concurrency:
  tao_py_py_concurrency_workflow

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: develops-tao-pypy
      SLACK_FOOTER: ""

    steps:
    - name: Confirm
      run: |
        ls -la
        python -V
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Poetry Version
      run: |
        poetry --version
    - name: Poetry Install Dependencies
      run: |
        poetry install --no-root
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run test
      run: | 
        pipenv run pytest tests
    - name: Slack Notification on Success
      uses: rtCamp/action-slack-notify@v2.2.0
      if: success()
      env:
        SLACK_USERNAME: Unit Test
        SLACK_TITLE: Unit Test Successed !!
        SLACK_COLOR: good
        SLACK_ICON_EMOJI: ":white_check_mark:"

    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.2.0
      if: failure()
      env:
        SLACK_USERNAME: Unit Test
        SLACK_TITLE: Unit Test Failed !!
        SLACK_COLOR: danger
        SLACK_ICON_EMOJI: ":fire:"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: develops-tao-pypy
      SLACK_FOOTER: ":rocket:"

    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy Action
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SFTP_USER_NAME }}
          server: ${{ secrets.SFTP_SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          port: 10022
          local_path: './'
          remote_path: '/home/maasaablog/maasaablog.com/public_html/dev.maasaablog.com/tao-pypy'
    
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2.2.0
        if: success()
        env:
          SLACK_USERNAME: Deploy
          SLACK_TITLE: Deploy Successed !!
          SLACK_COLOR: good
          SLACK_ICON_EMOJI: ":white_check_mark:"

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_USERNAME: Deploy
          SLACK_TITLE: Deploy Failed !!
          SLACK_COLOR: danger
          SLACK_ICON_EMOJI: ":fire:"
